# Generated by Django 4.2.10 on 2024-06-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_doctorsorusers_doctor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifications',
            name='university_and_years',
            field=models.TextField(blank=True, null=True),
        ),
    ]
