# Generated by Django 4.2.10 on 2024-06-18 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_remove_services_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_cate', to='service.services')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_doctor', to='service.serviecategory')),
            ],
        ),
        migrations.CreateModel(
            name='SerivePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_price', to='service.serviecategory')),
            ],
        ),
    ]
