# Generated by Django 4.2.10 on 2024-06-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_serviecategory_servicedoctor_seriveprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviecategory',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
